#! /usr/bin/env bash

# Purdue CS Bridge Gradescope Autograder
# >> run_autograder
#
# Description:
#   This script runs when a student
#   uploads their code to Gradescope.
#
# Last updated:
#   03/04/2021

# Declare paths
autograder="/autograder/source/autograder.jar"
submission_output="/autograder/compiled_submission"
results_file="/autograder/results/results.json"

# Set script to exit if error occurs
set -e

# Open submission
cd /autograder/submission

# Find submitted files
java_files=$( find -- * -type f -name "*.java" )

# Compile student submission
# If the compile fails for any reason, invoke the show_compile_errors.py script and exit
# Note: $java_files is being split by word, which is why it is not in quotes. We
#       stopped using an array of files due to the compiler having issues with flags
#       and not displaying a useful error message. (disabled SC2086 below)
# shellcheck disable=SC2086
javac -encoding UTF-8 -d $submission_output $java_files 2> compile.log \
  || { python3 /autograder/source/show_compile_errors.py < compile.log ; exit 1; }

# Run the autograder
# Note: $autograder comes before $submission_output to guard
#       against class injection. The autograder JAR should not
#       contain compiled starter code (otherwise the starter code
#       will take precedence over the submission).
java -cp $autograder:$submission_output TestRunner > $results_file
