name: CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.2.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t $GITHUB_REPOSITORY:latest .

      - name: Deploy to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $GITHUB_REPOSITORY:latest

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.2.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://hub.docker.com/repository/docker/$GITHUB_REPOSITORY/tags
